rules:
  - branch: main
    enforce_admins: true
    required_status_checks:
      strict: true
      contexts:
        - backend
        - frontend
        - coverage
        - preflight
        - validate
    required_pull_request_reviews:
      required_approving_review_count: 1