# GitHub Branch Protection Rules (managed via code)
# Apply these in Settings > Branches > Branch protection rules

rules:
  - pattern: "main"
    required_status_checks:
      strict: true
      contexts:
        - "CI Preflight"
        - "Render Deploy with Smoke Test"
        - "CCF Validation"
    enforce_admins: true
    required_pull_request_reviews:
      dismiss_stale_reviews: true
      required_approving_review_count: 1
    restrictions: null