coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
      backend:
        target: 90%
      frontend:
        target: 80%
      backend-js:
        target: 80%
      e2e:
        informational: true
    patch:
      default:
        target: 80%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true

github_checks:
  annotations: true

flags:
  frontend:
    paths:
      - src/
      - v2/
    carryforward: true
  backend:
    paths:
      - backend/**/*.py
      - api.py
    carryforward: true
  backend-js:
    paths:
      - backend/**/*.js
    carryforward: true
  e2e:
    paths:
      - tests/e2e/
    carryforward: true

component_management:
  individual_components:
    - component_id: frontend
      name: Frontend
      paths:
        - src/
    - component_id: backend
      name: Backend (Python)
      paths:
        - backend/**/*.py
        - api.py
    - component_id: backend-js
      name: Backend (JS)
      paths:
        - backend/**/*.js
    - component_id: e2e
      name: E2E
      paths:
        - tests/e2e/
