version: "3.9"

services:
  backend:
    build: .
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - qdrant

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev -- --host 0.0.0.0 --port 5173
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend

  qdrant:
    image: qdrant/qdrant:v1.9.1
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
