services:
  - type: web
    name: websiteos
    env: python
    buildCommand: |
      pip install -r requirements.txt
      npm install && npm run build
      mv dist ./dist  # ✅ persist dist so FastAPI can serve it
      # ✅ CI/CD pre-check: fail if dist/index.html or dist/assets is missing
      test -f dist/index.html && test -d dist/assets
    startCommand: uvicorn api:app --host 0.0.0.0 --port 10000
    healthCheckPath: /api/health
    routes:
      - type: rewrite
        source: /websitos/(.*)
        destination: /websitos
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PYTHON_VERSION
        value: 3.11
