services:
  - type: web
    name: websiteos
    env: python
    buildCommand: |
      pip install -r requirements.txt
      npm install && npm run build
    startCommand: uvicorn api:app --host 0.0.0.0 --port 10000
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PYTHON_VERSION
        value: 3.11
