services:
  - type: web
    name: websiteos
    env: python
    buildCommand: |
      # Clean caches
      rm -rf dist node_modules .vite .cache || true

      # Install backend + frontend deps
      pip install -r requirements.txt
      npm install --legacy-peer-deps

      # Run build
      npm run build || { echo "❌ Vite build failed"; exit 1; }

      echo "==== dist top-level (immediately after build) ===="
      ls -lh dist || true

      echo "==== dist/assets (immediately after build) ===="
      ls -lh dist/assets || echo "⚠️ dist/assets missing after build"

      echo "==== recursive dist tree (3 levels) ===="
      find dist -maxdepth 3 -type f -print || true

      echo "==== index.html head ===="
      head -n 20 dist/index.html || true

      echo "==== JS bundles (with size + SHA256) ===="
      for f in $(find dist -type f -name "*.js"); do
        sha=$(sha256sum $f | cut -c1-12)
        ls -lh $f
        echo "🔑 hash=$sha"
      done || true

      echo "==== Environment Info ===="
      node -v
      npm -v
      npx vite --version || true

      # Verify required files exist
      test -f dist/index.html || (echo "❌ dist/index.html missing" && exit 1)
      test -s dist/index.html || (echo "❌ index.html exists but is empty" && exit 1)
      if ! find dist -type f -name "*.js" | grep -q .; then
        echo "❌ No JS bundle generated"; exit 1;
      fi

      echo "✅ Final dist structure:" && ls -R dist
    startCommand: uvicorn api:app --host 0.0.0.0 --port 10000
    healthCheckPath: /api/health
    routes:
      - type: rewrite
        source: /websitos/(.*)
        destination: /websitos
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PYTHON_VERSION
        value: 3.11
