name: "Setup Dependencies"
description: "Install GitHub CLI and jq for workflows"
runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Run setup script
      shell: bash
      run: ./setup-deps.sh