#!/bin/sh

# Get changed files between local HEAD and remote main
CHANGED_FILES=$(git diff --name-only origin/main...HEAD)

# Skip checks if only GitHub workflow files are changed or if commit message contains 'force push'
if echo "$CHANGED_FILES" | grep -qE '(^|/)\.github/workflows/'; then
  echo "[Husky] Skipping checks for workflow-only push"
  exit 0
fi

if git log -1 --pretty=%B | grep -qi 'force push'; then
  echo "[Husky] Skipping checks for force push commit"
  exit 0
fi

# Otherwise run normal checks
npm run lint
npm test