name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-json-report black mypy requests

      - name: Validate environment variables
        run: python env_validator.py

      - name: Black format check
        run: black --check .

      - name: Type check (mypy)
        run: mypy api.py || true  # not strict yet

      - name: Run unit tests (pytest)
        run: pytest --maxfail=1 --disable-warnings -q --json-report --json-report-file=pytest-report.json || true

      - name: API smoke test
        run: |
          uvicorn api:app --host 0.0.0.0 --port 8000 > uvicorn.log 2>&1 &
          sleep 5
          curl -f http://localhost:8000/api/health
          curl -f http://localhost:8000/api/status

      - name: Validate OpenAPI contract
        run: |
          uvicorn api:app --host 0.0.0.0 --port 8000 > uvicorn_openapi.log 2>&1 &
          sleep 5
          python scripts/validate_openapi.py || true

      - name: Collect CI artifacts
        if: always()
        run: |
          mkdir -p ci_artifacts/backend
          cp -r pytest-report.json uvicorn.log uvicorn_openapi.log || true ci_artifacts/backend/

      - name: Upload backend artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: backend-artifacts
          path: ci_artifacts/backend