name: Backend Checks

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: [black, mypy, pytest, flake8]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ${{ matrix.task }}
        run: |
          mkdir -p logs
          if [ "${{ matrix.task }}" == "pytest" ]; then
            pytest --maxfail=1 --disable-warnings -q --json-report --json-report-file=logs/pytest-report.json 2>&1 | tee logs/pytest.log
          elif [ "${{ matrix.task }}" == "flake8" ]; then
            flake8 . | tee logs/flake8.log
          elif [ "${{ matrix.task }}" == "mypy" ]; then
            mypy . | tee logs/mypy.log
          elif [ "${{ matrix.task }}" == "black" ]; then
            black --check . | tee logs/black.log
          fi

      - name: Upload backend logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-backend-${{ matrix.task }}
          path: logs
          retention-days: 3