name: Backend Checks

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: [black, mypy, pytest, flake8]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest-json-report flake8 mypy black

      - name: Run Pytest
        if: ${{ matrix.task == 'pytest' }}
        run: |
          pytest --maxfail=1 --disable-warnings -q --json-report --json-report-file=pytest-output.json || true
          python scripts/convert_pytest.py pytest-output.json pytest-report.json || echo '{"workflow":"backend-checks","job":"pytest","status":"success","errors":[],"warnings":[],"notices":[]}' > pytest-report.json

      - name: Upload Pytest summary
        if: ${{ always() && matrix.task == 'pytest' }}
        uses: actions/upload-artifact@v4
        with:
          name: backend-pytest-report
          path: pytest-report.json

      - name: Run Mypy
        if: ${{ matrix.task == 'mypy' }}
        run: |
          mypy . > mypy-output.txt 2>&1 || true
          python scripts/convert-mypy.py mypy-output.txt mypy-report.json || echo '{"workflow":"backend-checks","job":"mypy","status":"success","errors":[],"warnings":[],"notices":[]}' > mypy-report.json

      - name: Upload Mypy summary
        if: ${{ always() && matrix.task == 'mypy' }}
        uses: actions/upload-artifact@v4
        with:
          name: backend-mypy-report
          path: mypy-report.json

      - name: Run Flake8
        if: ${{ matrix.task == 'flake8' }}
        run: |
          flake8 . > flake8-output.txt 2>&1 || true
          python scripts/convert-flake8.py flake8-output.txt flake8-report.json || echo '{"workflow":"backend-checks","job":"flake8","status":"success","errors":[],"warnings":[],"notices":[]}' > flake8-report.json

      - name: Upload Flake8 summary
        if: ${{ always() && matrix.task == 'flake8' }}
        uses: actions/upload-artifact@v4
        with:
          name: backend-flake8-report
          path: flake8-report.json

      - name: Run Black
        if: ${{ matrix.task == 'black' }}
        run: |
          black --check . > black-output.txt 2>&1 || true
          python scripts/convert-black.py black-output.txt black-report.json || echo '{"workflow":"backend-checks","job":"black","status":"success","errors":[],"warnings":[],"notices":[]}' > black-report.json

      - name: Upload Black summary
        if: ${{ always() && matrix.task == 'black' }}
        uses: actions/upload-artifact@v4
        with:
          name: backend-black-report
          path: black-report.json

  call-diagnostics:
    needs: checks
    uses: ./.github/workflows/ci-diagnostics.yml
    secrets: inherit