name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-json-report mypy black

      - name: Black Check
        run: |
          black --check . --exclude '(Lib|venv|node_modules)' > black-results.txt 2>&1 || true
          cat black-results.txt
        continue-on-error: true
      - name: Upload Black Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: black-results
          path: black-results.txt

      - name: Mypy Check
        run: |
          mypy . --exclude '(Lib|venv|node_modules)' > mypy-results.txt 2>&1 || true
          cat mypy-results.txt
        continue-on-error: true
      - name: Upload Mypy Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mypy-results
          path: mypy-results.txt

      - name: Run Pytest
        run: pytest -vv --maxfail=1 --disable-warnings --json-report --json-report-file=pytest-report.json || true

      - name: Upload backend artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifacts
          path: |
            pytest-report.json
            .pytest_cache
            uvicorn.log
            uvicorn_openapi.log
          retention-days: 7

      - name: Upload pytest console log
        if: always()
        run: pytest -vv --maxfail=1 --disable-warnings > pytest-console.log 2>&1 || true
        shell: bash
      - name: Upload console log artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-console-log
          path: pytest-console.log