name: Enforce Branch Protection

on:
  pull_request:
    branches: [ main ]

jobs:
  enforce:
    runs-on: ubuntu-latest
    steps:
      - name: Require Preflight to Pass
        run: |
          echo "Checking CI Preflight status..."
          gh run list --workflow "CI Preflight" --branch ${{ github.head_ref }} --limit 1 --json status,conclusion
          # If last run is not successful, exit with error
          STATUS=$(gh run list --workflow "CI Preflight" --branch ${{ github.head_ref }} --limit 1 --json conclusion --jq '.[0].conclusion')
          if [ "$STATUS" != "success" ]; then
            echo "❌ CI Preflight must pass before merging."
            exit 1
          fi

      - name: Require Smoke Tests to Pass
        run: |
          echo "Checking Render Deploy + Smoke Test status..."
          gh run list --workflow "Render Deploy with Smoke Test" --branch ${{ github.head_ref }} --limit 1 --json status,conclusion
          STATUS=$(gh run list --workflow "Render Deploy with Smoke Test" --branch ${{ github.head_ref }} --limit 1 --json conclusion --jq '.[0].conclusion')
          if [ "$STATUS" != "success" ]; then
            echo "❌ Render Deploy + Smoke Test must pass before merging."
            exit 1
          fi