name: Enforce Branch Protection

on:
  pull_request:
    branches: [ main ]

jobs:
  enforce:
    runs-on: ubuntu-latest
    steps:
      - name: Setup GitHub CLI
        uses: cli/cli-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Require Frontend Checks to Pass
        run: |
          echo "Checking Frontend Checks status..."
          STATUS=$(gh run list --workflow "Frontend Checks" --branch ${{ github.head_ref }} --limit 1 --json conclusion --jq '.[0].conclusion')
          if [ "$STATUS" != "success" ]; then
            echo "::error file=.github/workflows/branch-protection.yml::Frontend Checks must pass before merging."
            exit 1
          fi

      - name: Require Backend Checks to Pass
        run: |
          echo "Checking Backend Checks status..."
          STATUS=$(gh run list --workflow "Backend Checks" --branch ${{ github.head_ref }} --limit 1 --json conclusion --jq '.[0].conclusion')
          if [ "$STATUS" != "success" ]; then
            echo "::error file=.github/workflows/branch-protection.yml::Backend Checks must pass before merging."
            exit 1
          fi