name: Enforce Branch Protection

on:
  pull_request:
    branches: [ main ]

jobs:
  enforce:
    runs-on: ubuntu-latest
    steps:
      - name: Require Frontend CI to Pass
        run: |
          echo "Checking Frontend CI status..."
          STATUS=$(gh run list --workflow "Frontend CI" --branch ${{ github.head_ref }} --limit 1 --json conclusion --jq '.[0].conclusion')
          if [ "$STATUS" != "success" ]; then
            echo "❌ Frontend CI must pass before merging."
            exit 1
          fi

      - name: Require Backend CI to Pass
        run: |
          echo "Checking Backend CI status..."
          STATUS=$(gh run list --workflow "Backend CI" --branch ${{ github.head_ref }} --limit 1 --json conclusion --jq '.[0].conclusion')
          if [ "$STATUS" != "success" ]; then
            echo "❌ Backend CI must pass before merging."
            exit 1
          fi