name: CCF Validation

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Debug list key directories
        run: |
          echo "Workspace: $GITHUB_WORKSPACE"
          echo "Listing repo root:"
          ls -R | head -50

      - name: Ensure validate-secrets.js exists
        run: |
          if [ -f "scripts/validate-secrets.js" ]; then
            chmod +x scripts/validate-secrets.js
            echo "✅ validate-secrets.js found and executable"
          else
            echo "⚠️ scripts/validate-secrets.js not found, skipping"
          fi

      - name: Validate required files exist
        run: |
          REQUIRED_FILES=( \
            ".github/ccf-manifest.md" \
            ".github/workflows/ci-preflight.yml" \
            ".github/workflows/pr-narrator.yml" \
            ".github/workflows/post-deploy-smoke.yml" \
            ".github/workflows/render-deploy.yml" \
            ".github/workflows/branch-protection.yml" \
            ".github/branch-protection-rules.yml" \
            "config/secrets.schema.json" )

          MISSING=0
          for f in "${REQUIRED_FILES[@]}"; do
            if [ ! -f "$f" ]; then
              echo "❌ Missing required file: $f"
              MISSING=1
            else
              echo "✅ Found: $f"
            fi
          done

          if [ "$MISSING" -eq 1 ]; then
            exit 1
          fi

      - name: Confirm manifest is up-to-date
        run: |
          if ! grep -q "### 🚀 Mapping to Implementation" .github/ccf-manifest.md; then
            echo "❌ ccf-manifest.md missing mapping section"
            exit 1
          fi
          echo "✅ Manifest mapping confirmed"