name: CCF Validation

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Validate required files exist
        run: |
          echo "Checking for required Continuous Confidence Framework components..."

          REQUIRED_FILES=( \
            ".github/ccf-manifest.md" \
            ".github/workflows/ci-preflight.yml" \
            ".github/workflows/pr-narrator.yml" \
            ".github/workflows/post-deploy-smoke.yml" \
            ".github/workflows/render-deploy.yml" \
            ".github/workflows/branch-protection.yml" \
            ".github/branch-protection-rules.yml" \
            "config/secrets.schema.json" \
            "scripts/validate-secrets.js" \
          )

          MISSING=0
          for f in "${REQUIRED_FILES[@]}"; do
            if [ ! -f "$f" ]; then
              echo "❌ Missing required file: $f"
              MISSING=1
            else
              echo "✅ Found: $f"
            fi
          done

          if [ "$MISSING" -eq 1 ]; then
            echo "❌ One or more CCF components are missing."
            exit 1
          else
            echo "✅ All required CCF components are present."
          fi

      - name: Confirm manifest is up-to-date
        run: |
          echo "Checking if .github/ccf-manifest.md contains mapping section..."
          if ! grep -q "## 🔄 Mapping to Implementation" .github/ccf-manifest.md; then
            echo "❌ ccf-manifest.md missing Mapping section."
            exit 1
          fi
          echo "✅ Manifest mapping confirmed."