name: CCF Validation

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Debug list key directories
        run: |
          echo "Workspace: $GITHUB_WORKSPACE"
          echo "Listing repo root:"
          ls -R | head -50

      - name: Ensure validate-secrets.js is executable
        run: |
          if [ -f "scripts/validate-secrets.js" ]; then
            git update-index --chmod=+x scripts/validate-secrets.js || true
            chmod +x scripts/validate-secrets.js
            echo "✅ validate-secrets.js marked executable"
          else
            echo "❌ scripts/validate-secrets.js is missing!"
            exit 1
          fi

      - name: Validate required files exist
        run: |
          echo "Checking for required Continuous Confidence Framework components..."

          REQUIRED_FILES=( \
            "$GITHUB_WORKSPACE/.github/ccf-manifest.md" \
            "$GITHUB_WORKSPACE/.github/workflows/ci-preflight.yml" \
            "$GITHUB_WORKSPACE/.github/workflows/pr-narrator.yml" \
            "$GITHUB_WORKSPACE/.github/workflows/post-deploy-smoke.yml" \
            "$GITHUB_WORKSPACE/.github/workflows/render-deploy.yml" \
            "$GITHUB_WORKSPACE/.github/workflows/branch-protection.yml" \
            "$GITHUB_WORKSPACE/.github/branch-protection-rules.yml" \
            "$GITHUB_WORKSPACE/config/secrets.schema.json" \
            "$GITHUB_WORKSPACE/scripts/validate-secrets.js" \
          )

          MISSING=0
          for f in "${REQUIRED_FILES[@]}"; do
            if [ ! -f "$f" ]; then
              echo "❌ Missing required file: $f"
              MISSING=1
            else
              echo "✅ Found: $f"
            fi
          done

          if [ "$MISSING" -eq 1 ]; then
            echo "❌ One or more CCF components are missing."
            exit 1
          else
            echo "✅ All required CCF components are present."
          fi

      - name: Confirm manifest is up-to-date
        run: |
          echo "Checking if .github/ccf-manifest.md contains mapping section..."
          if ! grep -q "## 🔄 Mapping to Implementation" .github/ccf-manifest.md; then
            echo "❌ ccf-manifest.md missing Mapping section."
            exit 1
          fi
          echo "✅ Manifest mapping confirmed."