name: Preflight Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  preflight:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          if [ -f package.json ]; then npm ci; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run lint (if available)
        run: |
          if npm run | grep -q "lint"; then npm run lint || true; else echo "No lint script"; fi > lint-results.txt

      - name: Run type-check (if available)
        run: |
          if npm run | grep -q "type-check"; then npm run type-check || true; else echo "No type-check script"; fi > ts-results.txt

      - name: Run JS tests (if available)
        run: |
          if npm run | grep -q "test"; then npm test || true; else echo "No JS tests"; fi > jest-results.txt

      - name: Run Python tests (if available)
        run: |
          if [ -f requirements.txt ]; then pytest || true; else echo "No Python tests"; fi > pytest-results.txt

      - name: Summarize preflight results
        run: |
          echo "Preflight checks completed" > results.txt
          cat lint-results.txt >> results.txt || true
          cat ts-results.txt >> results.txt || true
          cat jest-results.txt >> results.txt || true
          cat pytest-results.txt >> results.txt || true

      - name: Upload results artifact
        uses: actions/upload-artifact@v4
        with:
          name: preflight-results
          path: |
            results.txt
            lint-results.txt
            ts-results.txt
            jest-results.txt
            pytest-results.txt
          retention-days: 3