name: Preflight Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  preflight:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Debug workspace
        run: |
          echo "Current directory: $(pwd)"
          ls -R | head -50

      - name: Detect frontend directory
        id: detect-frontend
        run: |
          if [ -f package.json ]; then
            echo "found-root=true" >> $GITHUB_OUTPUT
          elif [ -f frontend/package.json ]; then
            echo "found-frontend=true" >> $GITHUB_OUTPUT
          else
            echo "no-frontend=true" >> $GITHUB_OUTPUT
          fi

      - name: Install dependencies
        run: |
          if [ "${{ steps.detect-frontend.outputs.found-root }}" == "true" ]; then
            npm ci
          elif [ "${{ steps.detect-frontend.outputs.found-frontend }}" == "true" ]; then
            cd frontend && npm ci
          else
            echo "No frontend found"
          fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run lint (if available)
        run: |
          if [ "${{ steps.detect-frontend.outputs.found-root }}" == "true" ]; then
            npm run lint || true
          elif [ "${{ steps.detect-frontend.outputs.found-frontend }}" == "true" ]; then
            cd frontend && npm run lint || true
          else
            echo "No lint script"
          fi > lint-results.txt

      - name: Run type-check (if available)
        run: |
          if [ "${{ steps.detect-frontend.outputs.found-root }}" == "true" ]; then
            npm run type-check || true
          elif [ "${{ steps.detect-frontend.outputs.found-frontend }}" == "true" ]; then
            cd frontend && npm run type-check || true
          else
            echo "No type-check script"
          fi > ts-results.txt

      - name: Run JS tests (if available)
        run: |
          if [ "${{ steps.detect-frontend.outputs.found-root }}" == "true" ]; then
            npm test || true
          elif [ "${{ steps.detect-frontend.outputs.found-frontend }}" == "true" ]; then
            cd frontend && npm test || true
          else
            echo "No JS tests"
          fi > jest-results.txt

      - name: Run Python tests (if available)
        run: |
          if [ -f requirements.txt ]; then pytest || true; else echo "No Python tests"; fi > pytest-results.txt

      - name: Summarize preflight results
        run: |
          echo "Preflight checks completed" > results.txt
          cat lint-results.txt >> results.txt || true
          cat ts-results.txt >> results.txt || true
          cat jest-results.txt >> results.txt || true
          cat pytest-results.txt >> results.txt || true

      - name: Upload results artifact
        uses: actions/upload-artifact@v4
        with:
          name: preflight-results
          path: |
            results.txt
            lint-results.txt
            ts-results.txt
            jest-results.txt
            pytest-results.txt
          retention-days: 3