name: Capture Failure Summary

on:
  workflow_call:
    inputs:
      job_name:
        required: true
        type: string
      step_name:
        required: false
        type: string
        default: "unknown-step"

jobs:
  failure-summary:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Collect failure info (only if run failed)
        if: failure()
        run: |
          mkdir -p summary
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          EXIT_CODE_FILE="exit_code.log"
          EXIT_CODE=$(cat $EXIT_CODE_FILE 2>/dev/null || echo "unknown")

          # Safe tails (capture last 50 lines)
          TAIL_STDERR=$(tail -n 50 stderr.log 2>/dev/null || echo "No stderr captured")
          TAIL_STDOUT=$(tail -n 50 stdout.log 2>/dev/null || echo "No stdout captured")

          cat > summary/failure-summary-${{ inputs.job_name }}.json <<EOF
          {
            "run_id": $GITHUB_RUN_ID,
            "job": "${{ inputs.job_name }}",
            "step": "${{ inputs.step_name }}",
            "exit_code": "$EXIT_CODE",
            "error": "$(echo "$TAIL_STDERR" | head -n 1)",
            "stdout_tail": $(echo "$TAIL_STDOUT" | jq -R -s -c 'split("\n")'),
            "stderr_tail": $(echo "$TAIL_STDERR" | jq -R -s -c 'split("\n")'),
            "git": {
              "commit": "${{ github.sha }}",
              "branch": "${{ github.ref_name }}",
              "pr_number": "${{ github.event.pull_request.number || '' }}"
            },
            "triggered_by": "${{ github.actor }}",
            "environment": {
              "os": "${{ runner.os }}",
              "node": "$(node -v || echo 'not installed')",
              "python": "$(python3 --version 2>/dev/null || echo 'not installed')"
            },
            "duration_seconds": $(( ( $(date +%s) - $(date -d "$GITHUB_RUN_STARTED_AT" +%s) ) 2>/dev/null || echo -1 )),
            "timestamp": "$TIMESTAMP"
          }
          EOF

          # Validate JSON
          cat summary/failure-summary-${{ inputs.job_name }}.json | jq . >/dev/null || echo "⚠️ Invalid JSON generated"

      - name: Upload failure summary
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failure-summary-${{ inputs.job_name }}
          path: summary/failure-summary-${{ inputs.job_name }}.json
          retention-days: 7