name: Capture Failure Summary

on:
  workflow_call:
    inputs:
      job_name:
        required: true
        type: string
      step_name:
        required: false
        type: string
        default: "unknown-step"

jobs:
  failure-summary:
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable problem matchers
        run: |
          echo "::add-matcher::.github/matchers/error.json"
          echo "::add-matcher::.github/matchers/python.json"
          echo "::add-matcher::.github/matchers/eslint.json"
          echo "::add-matcher::.github/matchers/ts.json"

      - name: Collect failure info (runs only if job failed)
        run: |
          mkdir -p summary logs
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          EXIT_CODE_FILE="exit_code.log"
          EXIT_CODE=$(cat $EXIT_CODE_FILE 2>/dev/null || echo "unknown")

          ALL_STDERR=$(find logs -name "*.stderr.log" -exec tail -n 50 {} + 2>/dev/null || echo "No stderr captured")
          ALL_STDOUT=$(find logs -name "*.stdout.log" -exec tail -n 50 {} + 2>/dev/null || echo "No stdout captured")

          FAILED_STEP=$(grep -i "Error" -m1 logs/*.stderr.log 2>/dev/null || echo "${{ inputs.step_name }}")

          TAGGED_ERROR=$(echo "$ALL_STDERR" | head -n 1)

          echo "::error file=.github/workflows/${{ github.workflow }}.yml,title=${{ inputs.job_name }} failed::$TAGGED_ERROR"

          cat > summary/failure-summary-${{ inputs.job_name }}.json <<EOF
          {
            "run_id": $GITHUB_RUN_ID,
            "job": "${{ inputs.job_name }}",
            "step": "$FAILED_STEP",
            "exit_code": "$EXIT_CODE",
            "error": "$TAGGED_ERROR",
            "stdout_tail": $(echo "$ALL_STDOUT" | jq -R -s -c 'split("\n")'),
            "stderr_tail": $(echo "$ALL_STDERR" | jq -R -s -c 'split("\n")'),
            "git": {
              "commit": "${{ github.sha }}",
              "branch": "${{ github.ref_name }}",
              "pr_number": "${{ github.event.pull_request.number || '' }}"
            },
            "triggered_by": "${{ github.actor }}",
            "duration_seconds": -1,
            "workflow_url": "https://github.com/${{ github.repository }}/actions/runs/$GITHUB_RUN_ID",
            "timestamp": "$TIMESTAMP"
          }
          EOF

      - name: Upload failure summary folder
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: failure-summary-${{ inputs.job_name }}
          path: summary/**
          retention-days: 1