name: Collect Failed Logs

on:
  push:
  pull_request:
  workflow_run:
    workflows: ["CI", "Build", "Test", "Deploy"] # 🔹 update with real workflow names
    types:
      - completed
  workflow_dispatch:

jobs:
  collect-logs:
    if: ${{ github.event.workflow_run.conclusion == 'failure' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4   # ✅ Checkout before local action
      - uses: ./.github/actions/setup-deps

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Fetch jobs JSON for this workflow run
        run: |
          mkdir -p collected_logs
          if [[ "${{ github.event_name }}" == "workflow_dispatch" || "${{ github.event_name }}" == "push" || "${{ github.event_name }}" == "pull_request" ]]; then
            echo "{}" > collected_logs/jobs.json
          else
            gh run view ${{ github.event.workflow_run.id }} \
              --repo ${{ github.repository }} \
              --json jobs > collected_logs/jobs.json
          fi

      - name: Extract failed jobs
        run: |
          if [[ -s collected_logs/jobs.json ]]; then
            jq '.jobs[] | select(.conclusion=="failure")' collected_logs/jobs.json > collected_logs/failed_jobs.json || echo "No failed jobs"
            cat collected_logs/failed_jobs.json || true
          else
            echo "Manual or push/PR trigger: skipping failed jobs extraction"
          fi

      - name: Collect failed step logs
        run: |
          mkdir -p collected_logs/steps
          if [[ -s collected_logs/jobs.json ]]; then
            for job_id in $(jq -r '.jobs[] | select(.conclusion=="failure") | .id' collected_logs/jobs.json); do
              echo "Downloading logs for failed job: $job_id"
              gh run view ${{ github.event.workflow_run.id }} \
                --repo ${{ github.repository }} \
                --job $job_id --log > collected_logs/steps/job-${job_id}.log || true
            done
          else
            echo "Push/PR or manual trigger: creating dummy log"
            echo "No workflow_run context, push/PR/manual trigger executed" > collected_logs/steps/manual-trigger.log
          fi

      - name: Compress failed logs
        run: tar -czf failed-logs-${{ github.run_id }}.tar.gz collected_logs

      - name: Upload failed logs artifact
        uses: actions/upload-artifact@v4
        with:
          name: failed-logs
          path: failed-logs-${{ github.run_id }}.tar.gz