name: Fetch Preflight Diagnostics

on:
  workflow_run:
    workflows: ["CI Preflight"]
    types:
      - completed

jobs:
  fetch-diagnostics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install adm-zip

      - name: Run Diagnostics Fetcher
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          node scripts/fetch-diagnostics.js | tee diagnostics-summary.txt

      - name: Upload Diagnostics Summary Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: diagnostics-summary
          path: diagnostics-summary.txt