name: Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          (npm ci >stdout.log 2>stderr.log) || exit_code=$?
          exit ${exit_code:-0}

      - name: Build
        run: |
          (npm run build >stdout.log 2>stderr.log) || exit_code=$?
          exit ${exit_code:-0}

  capture-failure:
    uses: ./.github/workflows/failure-summary.yml
    with:
      job_name: frontend
      step_name: Build
    needs: [frontend]