name: Frontend Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checks:
    name: ${{ matrix.task }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [lint, prettier, type-check, test:unit]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run ESLint
        if: matrix.task == 'lint'
        run: |
          npx eslint src v2 ops --format json --output-file eslint-report.json || true
          if [ ! -f eslint-report.json ]; then echo '{}' > eslint-report.json; fi

      - name: Upload ESLint report
        if: always() && matrix.task == 'lint'
        uses: actions/upload-artifact@v4
        with:
          name: frontend-eslint-report
          path: eslint-report.json
          retention-days: 14

      - name: Run Prettier
        if: matrix.task == 'prettier'
        run: |
          npx prettier --check . > prettier-report.txt || true
          if [ ! -f prettier-report.txt ]; then echo 'No Prettier output' > prettier-report.txt; fi

      - name: Upload Prettier report
        if: always() && matrix.task == 'prettier'
        uses: actions/upload-artifact@v4
        with:
          name: frontend-prettier-report
          path: prettier-report.txt
          retention-days: 14

      - name: Run TypeScript type-check
        if: matrix.task == 'type-check'
        run: |
          npx tsc -p tsconfig.ci.json --noEmit --skipLibCheck > tsc-report.txt 2>&1 || true
          if [ ! -f tsc-report.txt ]; then echo 'No TSC output' > tsc-report.txt; fi

      - name: Upload TSC report
        if: always() && matrix.task == 'type-check'
        uses: actions/upload-artifact@v4
        with:
          name: frontend-tsc-report
          path: tsc-report.txt
          retention-days: 14

      - name: Run Jest unit tests
        if: matrix.task == 'test:unit'
        run: |
          npx jest --json --outputFile=jest-report.json --reporters=default --reporters=jest-github-actions-reporter || true
          if [ ! -f jest-report.json ]; then echo '{}' > jest-report.json; fi

      - name: Upload Jest results
        if: always() && matrix.task == 'test:unit'
        uses: actions/upload-artifact@v4
        with:
          name: frontend-jest-results
          path: jest-report.json
          retention-days: 14