name: Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  frontend:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Debug workspace
        run: |
          echo "Current directory: $(pwd)"
          ls -R | head -50

      - name: Detect frontend directory
        id: detect-frontend
        run: |
          if [ -f package.json ]; then
            echo "found-root=true" >> $GITHUB_OUTPUT
          elif [ -f frontend/package.json ]; then
            echo "found-frontend=true" >> $GITHUB_OUTPUT
          else
            echo "no-frontend=true" >> $GITHUB_OUTPUT
          fi

      - name: Install dependencies
        run: |
          if [ "${{ steps.detect-frontend.outputs.found-root }}" == "true" ]; then
            npm ci
          elif [ "${{ steps.detect-frontend.outputs.found-frontend }}" == "true" ]; then
            cd frontend && npm ci
          else
            echo "No frontend found"
          fi

      - name: Run frontend checks
        run: |
          if [ "${{ steps.detect-frontend.outputs.found-root }}" == "true" ]; then
            npm run lint || true
            npm run type-check || true
            npm run test:ci || npm test || true
          elif [ "${{ steps.detect-frontend.outputs.found-frontend }}" == "true" ]; then
            cd frontend
            npm run lint || true
            npm run type-check || true
            npm run test:ci || npm test || true
          else
            echo "No frontend to check"
          fi

      - name: Build frontend
        run: |
          if [ "${{ steps.detect-frontend.outputs.found-root }}" == "true" ]; then
            npm run build
          elif [ "${{ steps.detect-frontend.outputs.found-frontend }}" == "true" ]; then
            cd frontend && npm run build
          else
            echo "No frontend to build"
          fi

      - name: Upload frontend artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifacts
          path: |
            build/
            coverage/coverage-summary.json
            jest-report.json
            dist
          retention-days: 7