name: Frontend Checks

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: [lint, prettier, type-check, test-unit, test-e2e]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        if: ${{ matrix.task == 'lint' }}
        run: |
          pnpm exec eslint src v2 ops --format json --output-file eslint-output.json || true
          node Scripts/convert-eslint.js eslint-output.json eslint-report.json || echo '{"workflow":"frontend-checks","job":"lint","status":"success","errors":[],"warnings":[],"notices":[]}' > eslint-report.json
          echo "📂 Dumping eslint-report.json for debug"
          cat eslint-report.json || true
          mkdir -p summaries && mv eslint-report.json summaries/

      - name: Run Prettier
        if: ${{ matrix.task == 'prettier' }}
        run: |
          pnpm exec prettier --check . > prettier-output.txt 2>&1 || true
          node Scripts/convert-prettier.js prettier-output.txt prettier-report.json || echo '{"workflow":"frontend-checks","job":"prettier","status":"success","errors":[],"warnings":[],"notices":[]}' > prettier-report.json
          echo "📂 Dumping prettier-report.json for debug"
          cat prettier-report.json || true
          mkdir -p summaries && mv prettier-report.json summaries/

      - name: Run TypeScript type-check
        if: ${{ matrix.task == 'type-check' }}
        run: |
          pnpm exec tsc -p tsconfig.ci.json --noEmit --skipLibCheck > tsc-output.txt 2>&1 || true
          node Scripts/convert-tsc.js tsc-output.txt tsc-report.json || echo '{"workflow":"frontend-checks","job":"tsc","status":"success","errors":[],"warnings":[],"notices":[]}' > tsc-report.json
          echo "📂 Dumping tsc-report.json for debug"
          cat tsc-report.json || true
          mkdir -p summaries && mv tsc-report.json summaries/

      - name: Run Jest unit tests
        if: ${{ matrix.task == 'test-unit' }}
        run: |
          pnpm exec jest --coverage --json --outputFile=jest-output.json || true
          node Scripts/convert-jest.js jest-output.json jest-report.json || echo '{"workflow":"frontend-checks","job":"jest-unit","status":"success","errors":[],"warnings":[],"notices":[]}' > jest-report.json
          echo "📂 Dumping jest-report.json for debug"
          cat jest-report.json || true
          mkdir -p summaries && mv jest-report.json summaries/

      - name: Run Playwright E2E tests
        if: ${{ matrix.task == 'test-e2e' }}
        shell: bash {0}
        run: |
          pnpm exec playwright install --with-deps || true
          (pnpm exec playwright test 2>&1 | tee playwright-output.txt) || true
          echo "${PIPESTATUS[0]}" > exit-code.txt || true
          (npx nyc report --reporter=json-summary --report-dir=coverage/e2e) || true

          # Always try converter, fallback if it fails
          if ! node Scripts/convert-playwright.cjs playwright-output.txt coverage/e2e/coverage-summary.json playwright-report.json; then
            echo '{"workflow":"frontend-checks","job":"test-e2e","status":"failure","errors":[{"message":"Converter failed or produced no output"}],"warnings":[],"notices":[]}' > playwright-report.json
          fi

          echo "📂 Dumping playwright-report.json for debug"
          cat playwright-report.json || true

          mkdir -p summaries
          mv playwright-report.json summaries/ || true
          mv coverage/e2e/coverage-summary.json summaries/playwright-coverage-report.json || true

          # Collect raw logs inside summaries too (so Diagnostics can see them if needed)
          cp playwright-output.txt summaries/playwright-output.txt || true
          cp exit-code.txt summaries/exit-code.txt || true

          # Ensure dummy fallback exists
          if [ ! -f summaries/playwright-report.json ]; then
            echo '{"workflow":"frontend-checks","job":"test-e2e","status":"neutral","errors":[],"warnings":[],"notices":[{"message":"dummy fallback created"}]}' > summaries/playwright-report.json
          fi

          echo "📂 Contents of summaries before upload (with sizes):"
          ls -lah summaries || true

      - name: Upload frontend summaries
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-partial-${{ matrix.task }}
          path: summaries/
          retention-days: 2

      - name: Upload raw E2E logs
        if: ${{ matrix.task == 'test-e2e' }}
        uses: actions/upload-artifact@v4
        with:
          name: e2e-raw-logs
          path: raw-logs/
          retention-days: 2

  package-and-upload:
    runs-on: ubuntu-latest
    needs: checks
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all frontend job artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./downloaded

      - name: Collect frontend summaries
        run: |
          mkdir -p summaries
          find downloaded -type f -name "*-report.json" -exec cp {} summaries/ \;
          echo "📂 Collected summaries:" 
          ls -lah summaries || true

      - name: Upload combined frontend summaries
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-summaries
          path: summaries/
          retention-days: 2