name: Frontend Checks

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: [lint, type-check, test:unit, prettier]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Enable problem matchers
        continue-on-error: true
        run: |
          echo "::add-matcher::.github/matchers/error.json"
          echo "::add-matcher::.github/matchers/jest.json"
          echo "::add-matcher::.github/matchers/eslint.json"
          echo "::add-matcher::.github/matchers/ts.json"
          echo "::add-matcher::.github/matchers/generic-errors.json"

      - name: Install dependencies (npm ci)
        run: npm ci

      - name: Run ${{ matrix.task }}
        run: |
          echo "::group::🔎 Running task: ${{ matrix.task }}"
          EXIT=0
          if [ "${{ matrix.task }}" == "test:unit" ]; then
            npm run test:unit -- --runInBand --verbose --json --outputFile=jest-report.json --reporters=default --reporters=jest-github-actions-reporter || EXIT=$?
            if [ ! -f jest-report.json ]; then
              echo '{}' > jest-report.json
              echo "::warning file=frontend/tests::jest-report.json missing, test run may have crashed"
            fi
          elif [ "${{ matrix.task }}" == "lint" ]; then
            npx eslint src v2 ops --format json -o eslint-report.json --max-warnings=0 || EXIT=$?
            if [ ! -f eslint-report.json ]; then
              echo '{}' > eslint-report.json
              echo "::warning file=frontend/src::eslint-report.json missing, lint run may have crashed"
            fi
          elif [ "${{ matrix.task }}" == "type-check" ]; then
            npx tsc --noEmit --pretty false || EXIT=$?
          elif [ "${{ matrix.task }}" == "prettier" ]; then
            npx prettier --check . | sed 's/^/::warning::/' || true
          fi
          echo "::endgroup::"
          exit $EXIT
        continue-on-error: ${{ matrix.task == 'lint' || matrix.task == 'prettier' }}

      - name: Upload Jest results artifact
        if: always() && matrix.task == 'test:unit'
        uses: actions/upload-artifact@v4
        with:
          name: frontend-jest-results
          path: jest-report.json
          retention-days: 14

      - name: Upload ESLint results artifact
        if: always() && matrix.task == 'lint'
        uses: actions/upload-artifact@v4
        with:
          name: frontend-eslint-results
          path: eslint-report.json
          retention-days: 14

  build:
    runs-on: ubuntu-latest
    needs: checks
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies (npm ci)
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Upload frontend artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifacts
          path: |
            coverage/lcov.info
            coverage/coverage-summary.json
            jest-report.json
            eslint-report.json
          retention-days: 14

  e2e:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies (npm ci)
        run: npm ci

      - name: Run Playwright tests
        run: npm run test:e2e