name: Frontend Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checks:
    name: ${{ matrix.task }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [lint, prettier, type-check, test:unit, test:e2e]
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Cache pnpm
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Enable problem matchers
        run: |
          echo "::add-matcher::.github/matchers/eslint.json"
          echo "::add-matcher::.github/matchers/jest.json"
          echo "::add-matcher::.github/matchers/ts.json"

      - name: Run ESLint
        if: ${{ matrix.task == 'lint' }}
        run: |
          pnpm exec eslint src v2 ops --format json --output-file eslint-output.json || true
          node scripts/convert-eslint.js eslint-output.json eslint-report.json

      - name: Upload ESLint summary
        if: ${{ always() && matrix.task == 'lint' }}
        uses: actions/upload-artifact@v4
        with:
          name: frontend-eslint-report
          path: eslint-report.json
          retention-days: 14

      - name: Run Prettier
        if: ${{ matrix.task == 'prettier' }}
        run: |
          pnpm exec prettier --check . > prettier-output.txt 2>&1 || true
          node scripts/convert-prettier.js prettier-output.txt prettier-report.json

      - name: Upload Prettier summary
        if: ${{ always() && matrix.task == 'prettier' }}
        uses: actions/upload-artifact@v4
        with:
          name: frontend-prettier-report
          path: prettier-report.json
          retention-days: 14

      - name: Run TypeScript type-check
        if: ${{ matrix.task == 'type-check' }}
        run: |
          pnpm exec tsc -p tsconfig.ci.json --noEmit --skipLibCheck | tee tsc-output.txt || true
          node -e 'const fs=require("fs"); const lines=fs.readFileSync("tsc-output.txt","utf-8").split("\n"); const summary={workflow:"frontend-checks",job:"tsc",status:"success",errors:[],warnings:[],notices:[]}; lines.forEach(l=>{if(l.includes("error")){summary.errors.push({file:"unknown",line:null,column:null,message:l,rule:"tsc",severity:"error"});summary.status="failure"}}); fs.writeFileSync("tsc-report.json",JSON.stringify(summary,null,2));'

      - name: Upload TSC summary
        if: ${{ always() && matrix.task == 'type-check' }}
        uses: actions/upload-artifact@v4
        with:
          name: frontend-tsc-report
          path: tsc-report.json
          retention-days: 14

      - name: Run Jest unit tests
        if: ${{ matrix.task == 'test:unit' }}
        run: |
          pnpm exec jest --coverage --json --outputFile=jest-output.json || true
          node -e 'const fs=require("fs"); const raw=fs.existsSync("jest-output.json")?JSON.parse(fs.readFileSync("jest-output.json","utf-8")):{testResults:[]}; const summary={workflow:"frontend-checks",job:"jest-unit",status:"success",errors:[],warnings:[],notices:[]}; raw.testResults.forEach(t=>{if(t.status==="failed"){summary.errors.push({file:t.name||"unknown",line:null,column:null,message:"Test failed",rule:"jest",severity:"error"});summary.status="failure"}}); fs.writeFileSync("jest-report.json",JSON.stringify(summary,null,2));'

      - name: Upload Jest summary
        if: ${{ always() && matrix.task == 'test:unit' }}
        uses: actions/upload-artifact@v4
        with:
          name: frontend-jest-report
          path: jest-report.json
          retention-days: 14

      - name: Install Playwright Browsers
        if: ${{ matrix.task == 'test:e2e' }}
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright E2E tests with coverage
        if: ${{ matrix.task == 'test:e2e' }}
        run: |
          pnpm exec nyc --reporter=lcov --report-dir=coverage/e2e pnpm exec playwright test || true
          node scripts/convert-jest-coverage.js coverage/e2e/coverage-summary.json playwright-coverage-report.json

      - name: Upload Playwright coverage summary
        if: ${{ always() && matrix.task == 'test:e2e' }}
        uses: actions/upload-artifact@v4
        with:
          name: frontend-playwright-report
          path: playwright-coverage-report.json
          retention-days: 14

  call-diagnostics:
    needs: checks
    uses: ./.github/workflows/ci-diagnostics.yml
    secrets: inherit