name: Frontend Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checks:
    name: ${{ matrix.task }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [lint, prettier, type-check, test:unit, test:e2e]
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Cache pnpm
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        if: ${{ matrix.task == 'lint' }}
        run: |
          pnpm exec eslint src v2 ops --format json --output-file eslint-output.json || true
          node scripts/convert-eslint.js eslint-output.json eslint-report.json || echo '{"workflow":"frontend-checks","job":"lint","status":"success","errors":[],"warnings":[],"notices":[]}' > eslint-report.json

      - name: Upload ESLint summary
        if: ${{ always() && matrix.task == 'lint' }}
        uses: actions/upload-artifact@v4
        with:
          name: frontend-eslint-report
          path: eslint-report.json

      - name: Run Prettier
        if: ${{ matrix.task == 'prettier' }}
        run: |
          pnpm exec prettier --check . > prettier-output.txt 2>&1 || true
          node scripts/convert-prettier.js prettier-output.txt prettier-report.json || echo '{"workflow":"frontend-checks","job":"prettier","status":"success","errors":[],"warnings":[],"notices":[]}' > prettier-report.json

      - name: Upload Prettier summary
        if: ${{ always() && matrix.task == 'prettier' }}
        uses: actions/upload-artifact@v4
        with:
          name: frontend-prettier-report
          path: prettier-report.json

      - name: Run TypeScript type-check
        if: ${{ matrix.task == 'type-check' }}
        run: |
          pnpm exec tsc -p tsconfig.ci.json --noEmit --skipLibCheck > tsc-output.txt 2>&1 || true
          node scripts/convert-tsc.js tsc-output.txt tsc-report.json || echo '{"workflow":"frontend-checks","job":"tsc","status":"success","errors":[],"warnings":[],"notices":[]}' > tsc-report.json

      - name: Upload TSC summary
        if: ${{ always() && matrix.task == 'type-check' }}
        uses: actions/upload-artifact@v4
        with:
          name: frontend-tsc-report
          path: tsc-report.json

      - name: Run Jest unit tests
        if: ${{ matrix.task == 'test:unit' }}
        run: |
          pnpm exec jest --coverage --json --outputFile=jest-output.json || true
          node scripts/convert-jest.js jest-output.json jest-report.json || echo '{"workflow":"frontend-checks","job":"jest-unit","status":"success","errors":[],"warnings":[],"notices":[]}' > jest-report.json

      - name: Upload Jest summary
        if: ${{ always() && matrix.task == 'test:unit' }}
        uses: actions/upload-artifact@v4
        with:
          name: frontend-jest-report
          path: jest-report.json

      - name: Install Playwright Browsers
        if: ${{ matrix.task == 'test:e2e' }}
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright E2E tests with coverage
        if: ${{ matrix.task == 'test:e2e' }}
        run: |
          pnpm exec nyc --reporter=lcov --report-dir=coverage/e2e pnpm exec playwright test || true
          node scripts/convert-jest-coverage.js coverage/e2e/coverage-summary.json playwright-coverage-report.json || echo '{"workflow":"frontend-checks","job":"playwright-e2e","status":"success","errors":[],"warnings":[],"notices":[]}' > playwright-coverage-report.json

      - name: Upload Playwright coverage summary
        if: ${{ always() && matrix.task == 'test:e2e' }}
        uses: actions/upload-artifact@v4
        with:
          name: frontend-playwright-report
          path: playwright-coverage-report.json

  call-diagnostics:
    needs: checks
    uses: ./.github/workflows/ci-diagnostics.yml
    secrets: inherit