name: Frontend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'v2/**'
      - 'package.json'
      - 'vite.config.js'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'v2/**'
      - 'package.json'
      - 'vite.config.js'
      - '.github/workflows/frontend-ci.yml'
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        task: [lint, type-check, test:unit]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies (npm ci)
        run: npm ci

      - name: Enable problem matchers
        uses: ./.github/actions/setup-matchers

      - name: Run ${{ matrix.task }}
        run: npm run ${{ matrix.task }}
        continue-on-error: ${{ matrix.task == 'lint' }}

  build:
    runs-on: ubuntu-latest
    needs: checks
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies (npm ci)
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Upload frontend artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifacts
          path: |
            coverage/lcov.info
            coverage/coverage-summary.json
            jest-report.json
          retention-days: 7

  e2e:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies (npm ci)
        run: npm ci

      - name: Run Playwright tests
        run: npm run test:e2e

  capture-failure:
    if: always()
    needs: [build, e2e]
    uses: ./.github/workflows/failure-summary.yml
    with:
      job_name: frontend
      step_name: build