name: Ops Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'ops/**'
      - 'toolkits/**'
      - '.github/workflows/ops-pipeline.yml'
  workflow_dispatch:

jobs:
  ops:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false
          persist-credentials: false

      - name: Load default env file
        run: cp .env.example .env

      - name: Enable problem matchers
        run: echo "::add-matcher::.github/matchers/error.json"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Cache pnpm
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          echo ">>> Installing dependencies"
          pnpm install --frozen-lockfile || { echo "::error::pnpm install failed"; exit 1; }
          python -m pip install --upgrade pip
          pip install --prefer-binary -r requirements.txt || { echo "::error::pip install failed"; exit 1; }
          pip install pytest pytest-github-actions-annotate-failures

      - name: Run Ops Cycle
        run: |
          echo ">>> Starting Ops Cycle"
          if ! pnpm opscycle; then
            echo "::error file=ops/scripts/opsCycle.ts::Ops cycle failed"
            exit 1
          fi
          echo ">>> Finished Ops Cycle"

      - name: Run Security Scan
        run: |
          echo ">>> Starting Security Scan"
          if ! pnpm secscan; then
            echo "::warning file=scripts/scan-secrets.ts::Security scan flagged issues"
            exit 0
          fi
          echo ">>> Finished Security Scan"