name: OpsPipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ops-pipeline:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # PowerShell Core (pwsh) is already on the runner — no setup action needed.
      - name: Run OpsPipeline
        shell: pwsh
        run: |
          pwsh -v
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
          if (-not (Test-Path .\OpsPipeline.ps1)) {
            Write-Error "OpsPipeline.ps1 not found at repo root"
            exit 1
          }
          ./OpsPipeline.ps1 -FailFast