name: OpsPipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ops-pipeline:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Enable problem matchers
        uses: ./.github/workflows/setup-matchers.yml

      # Ensure PowerShell Core is available and validate environment
      - name: Verify pwsh availability
        shell: pwsh
        run: pwsh -v

      - name: Run OpsPipeline
        shell: pwsh
        run: |
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
          if (-not (Test-Path .\OpsPipeline.ps1)) {
            Write-Error "OpsPipeline.ps1 not found at repo root"
            exit 1
          }
          ./OpsPipeline.ps1 -FailFast