name: Ops Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'ops/**'
      - 'toolkits/**'
      - '.github/workflows/ops-pipeline.yml'
  workflow_dispatch:

jobs:
  ops:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Enable problem matchers
        run: echo "::add-matcher::.github/matchers/error.json"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          npm ci --legacy-peer-deps
          python -m pip install --upgrade pip
          pip install --prefer-binary -r requirements.txt
          pip install pytest pytest-github-actions-annotate-failures

      - name: Run Ops Cycle
        run: |
          echo "::group:: Running Ops Cycle"
          if ! npm run opscycle; then
            echo "::error file=ops/scripts/opsCycle.ts::Ops cycle failed"
            exit 1
          fi
          echo "::endgroup::"

      - name: Run Security Scan
        run: |
          echo "::group:: Running Security Scan"
          if ! npm run secscan; then
            echo "::warning file=scripts/scan-secrets.ts::Security scan flagged issues"
            exit 0
          fi
          echo "::endgroup::"