name: Post-Deploy Smoke Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # run every hour as a safety net

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Enable problem matchers
        uses: ./.github/actions/setup-matchers

      - name: Define endpoint check function
        run: |
          cat > check_endpoint.sh <<'EOF'
          #!/bin/bash
          URL=$1
          NAME=$2
          for i in {1..3}; do
            echo "Checking $NAME at $URL (attempt $i)..."
            RESPONSE=$(curl -s -w "HTTPSTATUS:%{http_code}" -o response.txt "$URL" || true)
            BODY=$(cat response.txt)
            STATUS=$(echo $RESPONSE | sed -e 's/.*HTTPSTATUS://')

            if [ "$STATUS" -eq 200 ]; then
              echo "✅ $NAME OK"
              rm -f response.txt
              exit 0
            else
              echo "⚠️ $NAME failed with status $STATUS"
              echo "Response body (truncated):"
              echo "$BODY" | head -n 20
              sleep 10
            fi
          done
          echo "::error::$NAME check failed after 3 attempts"
          exit 1
          EOF
          chmod +x check_endpoint.sh

      - name: Check API Health
        run: ./check_endpoint.sh https://websitos.onrender.com/api/health "API Health"

      - name: Check Extended Status
        run: ./check_endpoint.sh https://websitos.onrender.com/api/status "API Extended Status"

      - name: Check Root Health
        run: ./check_endpoint.sh https://websitos.onrender.com/health "Root Health"

      - name: Check Frontend Homepage
        run: ./check_endpoint.sh https://websitos.onrender.com/ "Frontend Homepage"

  capture-failure:
    if: failure()
    needs: [smoke]
    uses: ./.github/workflows/failure-summary.yml
    with:
      job_name: post-deploy-smoke
      step_name: endpoint-checks