name: Post-Deploy Smoke Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # run every hour as a safety net

jobs:
  smoke:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Enable problem matchers
        continue-on-error: true
        run: echo "::add-matcher::.github/matchers/error.json"

      - name: Define endpoint check function
        run: |
          cat > check_endpoint.sh <<'EOF'
          #!/bin/bash
          URL=$1
          NAME=$2
          for i in {1..3}; do
            echo "Checking $NAME at $URL (attempt $i)..."
            RESPONSE=$(curl -s -w "HTTPSTATUS:%{http_code}" -o response.txt "$URL" || true)
            BODY=$(cat response.txt)
            STATUS=$(echo $RESPONSE | sed -e 's/.*HTTPSTATUS://')

            if [ "$STATUS" -eq 200 ]; then
              echo "✅ $NAME OK"
              rm -f response.txt
              exit 0
            else
              echo "⚠️ $NAME failed with status $STATUS"
              echo "Response body (truncated):"
              echo "$BODY" | head -n 20
              echo "::warning file=.github/workflows/post-deploy-smoke.yml::Smoke check failed ($NAME, status $STATUS)"
              sleep 10
            fi
          done
          echo "::error::$NAME check failed after 3 attempts"
          if [ ! -f response.txt ]; then
            echo 'No response captured' > response.txt
          fi
          exit 1
          EOF
          chmod +x check_endpoint.sh

      - name: Check API Health
        run: ./check_endpoint.sh https://websitos.onrender.com/api/health "API Health"

      - name: Check Extended Status
        run: ./check_endpoint.sh https://websitos.onrender.com/api/status "API Extended Status"

      - name: Check Root Health
        run: ./check_endpoint.sh https://websitos.onrender.com/health "Root Health"

      - name: Check Frontend Homepage
        run: ./check_endpoint.sh https://websitos.onrender.com/ "Frontend Homepage"

      - name: Upload Smoke Test Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: post-deploy-smoke-logs
          path: response.txt
          retention-days: 7