name: Post-Deploy Smoke Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # run every hour as a safety net

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Check API Health
        run: |
          echo "Hitting /api/health..."
          for i in {1..3}; do
            if curl -sSf https://websitos.onrender.com/api/health; then
              echo "✅ /api/health OK"
              break
            else
              echo "Retrying..."
              sleep 10
            fi
          done

      - name: Check Extended Status
        run: |
          echo "Hitting /api/status..."
          for i in {1..3}; do
            if curl -sSf https://websitos.onrender.com/api/status; then
              echo "✅ /api/status OK"
              break
            else
              echo "Retrying..."
              sleep 10
            fi
          done

      - name: Check Root Health
        run: |
          echo "Hitting /health..."
          for i in {1..3}; do
            if curl -sSf https://websitos.onrender.com/health; then
              echo "✅ /health OK"
              break
            else
              echo "Retrying..."
              sleep 10
            fi
          done