name: Post-Deploy Smoke Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # run every hour as a safety net

jobs:
  smoke:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Enable problem matchers
        continue-on-error: true
        run: |
          echo "::add-matcher::.github/matchers/error.json"
          echo "::add-matcher::.github/matchers/generic-errors.json"

      - name: Define endpoint check function
        run: |
          cat > check_endpoint.sh <<'EOF'
          #!/bin/bash
          URL=$1
          NAME=$2
          MAX_RETRIES=5
          DELAY=5

          for i in $(seq 1 $MAX_RETRIES); do
            echo "Checking $NAME at $URL (attempt $i/$MAX_RETRIES)..."
            RESPONSE=$(curl -s -w "HTTPSTATUS:%{http_code}" -o response.txt "$URL" || true)
            BODY=$(cat response.txt)
            STATUS=$(echo $RESPONSE | sed -e 's/.*HTTPSTATUS://')

            if [ "$STATUS" -eq 200 ]; then
              echo "✅ $NAME OK"
              echo "$BODY" | head -n 20
              break
            else
              echo "⚠️ $NAME failed with status $STATUS"
              echo "Response body (truncated):"
              echo "$BODY" | head -n 20
              if [ $i -lt $MAX_RETRIES ]; then
                echo "Retrying in $DELAY seconds..."
                sleep $DELAY
                DELAY=$((DELAY*2))
              else
                echo "::error::$NAME check failed after $MAX_RETRIES attempts"
                exit 1
              fi
            fi
          done
          EOF
          chmod +x check_endpoint.sh

      - name: Check API Health
        run: ./check_endpoint.sh https://websitos.onrender.com/api/health "API Health"

      - name: Check Extended Status
        run: ./check_endpoint.sh https://websitos.onrender.com/api/status "API Extended Status"

      - name: Check Root Health
        run: ./check_endpoint.sh https://websitos.onrender.com/health "Root Health"

      - name: Check Frontend Homepage
        run: ./check_endpoint.sh https://websitos.onrender.com/ "Frontend Homepage"

      - name: Upload Smoke Test Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: post-deploy-smoke-logs
          path: response.txt
          retention-days: 14