name: Render Deploy with Smoke Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Enable problem matchers
        continue-on-error: true
        run: |
          echo "::add-matcher::.github/matchers/error.json"
          echo "::add-matcher::.github/matchers/generic-errors.json"

      - name: Trigger Render Deploy
        id: trigger
        run: |
          echo "Triggering Render deploy..."
          RESPONSE=$(curl -s -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "accept: application/json" \
            -H "content-type: application/json")
          echo "$RESPONSE"
          DEPLOY_ID=$(echo $RESPONSE | jq -r '.id')
          echo "deploy_id=$DEPLOY_ID" >> $GITHUB_OUTPUT

  smoke:
    runs-on: ubuntu-latest
    needs: deploy
    continue-on-error: true
    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Enable problem matchers
        continue-on-error: true
        run: |
          echo "::add-matcher::.github/matchers/error.json"
          echo "::add-matcher::.github/matchers/generic-errors.json"

      - name: Wait for Render Deploy to Complete
        run: |
          DEPLOY_ID=${{ needs.deploy.outputs.deploy_id }}
          echo "Waiting for Render deploy $DEPLOY_ID to complete..."

          for i in {1..30}; do
            STATUS=$(curl -s "https://api.render.com/v1/deploys/$DEPLOY_ID" \
              -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" | jq -r '.status')

            echo "Attempt $i: Status = $STATUS"

            if [ "$STATUS" == "live" ]; then
              echo "✅ Deploy is live"
              break
            fi

            if [ "$STATUS" == "failed" ]; then
              echo "::error::Deploy failed"
              exit 1
            fi

            sleep 10
          done

      - name: Define endpoint check function
        run: |
          cat > check_endpoint.sh <<'EOF'
          #!/bin/bash
          URL=$1
          NAME=$2
          for i in {1..3}; do
            echo "Checking $NAME at $URL (attempt $i)..."
            RESPONSE=$(curl -s -w "HTTPSTATUS:%{http_code}" -o response.txt "$URL" || true)
            BODY=$(cat response.txt)
            STATUS=$(echo $RESPONSE | sed -e 's/.*HTTPSTATUS://')

            if [ "$STATUS" -eq 200 ]; then
              echo "✅ $NAME OK"
              rm -f response.txt
              exit 0
            else
              echo "⚠️ $NAME failed with status $STATUS"
              echo "Response body (truncated):"
              echo "$BODY" | head -n 20
              sleep 10
            fi
          done
          echo "::error::$NAME check failed after 3 attempts"
          if [ ! -f response.txt ]; then
            echo 'No response captured' > response.txt
          fi
          exit 1
          EOF
          chmod +x check_endpoint.sh

      - name: Check API Health
        run: ./check_endpoint.sh https://websitos.onrender.com/api/health "API Health"

      - name: Check Extended Status
        run: ./check_endpoint.sh https://websitos.onrender.com/api/status "API Extended Status"

      - name: Check Root Health
        run: ./check_endpoint.sh https://websitos.onrender.com/health "Root Health"

      - name: Check Frontend Homepage
        run: ./check_endpoint.sh https://websitos.onrender.com/ "Frontend Homepage"

      - name: Upload Smoke Test Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-test-logs
          path: response.txt
          retention-days: 14