name: Test Failure Workflow

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  always-fail:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4   # ✅ Checkout before local action
      - uses: ./.github/actions/setup-deps
      - name: Force failure
        run: |
          echo "This job is designed to fail to test the failed-logs-collector"
          exit 1