name: U-DIG IT Log Reporter

on:
  workflow_run:
    workflows: ["WEBSITEOS CI/CD"]
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Get workflow run logs
        run: |
          curl -H "Authorization: Bearer ${{ secrets.UDIGIT_GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               -o logs.json \
               https://api.github.com/repos/udigitrentals/websitos/actions/runs/${{ github.event.workflow_run.id }}/logs

      - name: Upload logs to U-DIG IT
        run: |
          curl -X POST "https://your-udigit-endpoint.com/logs" \
          -H "Authorization: Bearer ${{ secrets.UDIGIT_GITHUB_TOKEN }}" \
          -F "file=@logs.json"
