name: Uptime Check

on:
  schedule:
    - cron: '0 */6 * * *' # every 6 hours
  workflow_dispatch:

jobs:
  uptime:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-deps

      - name: Check API health
        run: |
          curl -f https://websitos.onrender.com/api/health || exit 1

      - name: Check Frontend availability
        run: |
          curl -f https://websitos.onrender.com/websitos/ || exit 1