name: Uptime Check

on:
  schedule:
    - cron: '0 */6 * * *' # every 6 hours
  workflow_dispatch:

jobs:
  uptime:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check API health with retries
        run: |
          for i in {1..3}; do
            curl -f https://websitos.onrender.com/api/health && break || sleep 10
          done

      - name: Check Frontend availability with retries
        run: |
          for i in {1..3}; do
            curl -f https://websitos.onrender.com/websitos/ && break || sleep 10
          done