name: WEBSITEOS CI/CD

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.17.0
      - run: npm ci
      - run: npm run lint
      - run: npm run format:check

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.17.0
      - run: npm ci
      - run: npm test -- --coverage --watchAll=false

  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - run: pip install adodbapi
      - run: pytest --maxfail=1 --disable-warnings --cov=. --cov-fail-under=80

  qa-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.17.0
      - run: npm ci
      - run: npm run build
      - run: npx serve -s dist & # serve dist folder in background
      - run: npx lhci autorun --config=lighthouserc.json

  build-check:
    runs-on: ubuntu-latest
    needs: [lint-format, frontend-tests, backend-tests, qa-audit]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.17.0
      - run: npm ci
      - run: npm run build
      - run: docker build -t websiteos .

  deploy:
    runs-on: ubuntu-latest
    needs: [build-check]
    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST "https://api.render.com/deploy/${{ secrets.SERVICE_ID }}" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
